import { db } from './database';
import {
  Hospital,
  Block,
  Floor,
  Room,
  Department,
  User,
  Patient,
} from './types';

export function seedDatabase() {
  console.log('🌱 Initializing clean hospital infrastructure with 0 pre-existing patient entries...');

  const hospitalId = 'hosp-grh-01';
  const hospital: Hospital = {
    id: hospitalId,
    name: 'Government Rajaji General Hospital',
    location: 'Madurai, Tamil Nadu',
    state: 'Tamil Nadu',
    totalBeds: 1450,
    icuBedsAvailable: 8,
    emergencyBedsAvailable: 12,
    contactPhone: '+91 452 2532535',
    emergencyStatus: 'normal',
    createdAt: new Date().toISOString(),
  };

  const blocks: Block[] = [
    { id: 'blk-a', hospitalId, name: 'Block A', description: 'Main Administration, Entrance & Emergency Care' },
    { id: 'blk-b', hospitalId, name: 'Block B', description: 'Outpatient Specialty Clinics (OPD)' },
    { id: 'blk-c', hospitalId, name: 'Block C', description: 'Radiology, Diagnostics & Imaging Wing' },
  ];

  const floors: Floor[] = [
    { id: 'flr-a-g', blockId: 'blk-a', level: 0, name: 'Ground Floor' },
    { id: 'flr-b-g', blockId: 'blk-b', level: 0, name: 'Ground Floor' },
    { id: 'flr-b-1', blockId: 'blk-b', level: 1, name: '1st Floor' },
    { id: 'flr-c-g', blockId: 'blk-c', level: 0, name: 'Ground Floor' },
    { id: 'flr-c-1', blockId: 'blk-c', level: 1, name: '1st Floor' },
  ];

  const rooms: Room[] = [
    { id: 'rm-reg', blockId: 'blk-a', floorId: 'flr-a-g', roomNumber: 'Central Registration', name: 'Central Registration', category: 'Registration', color: 'yellow' },
    { id: 'rm-pharm', blockId: 'blk-a', floorId: 'flr-a-g', roomNumber: 'Central Pharmacy', name: 'Central Pharmacy', category: 'Pharmacy', color: 'purple' },
    { id: 'rm-emerg', blockId: 'blk-a', floorId: 'flr-a-g', roomNumber: 'Emergency Trauma Ward', name: 'Emergency Trauma Ward', category: 'Emergency', color: 'red' },
    { id: 'rm-cardio', blockId: 'blk-b', floorId: 'flr-b-1', roomNumber: 'Cardiology OPD Suite', name: 'Cardiology OPD Suite', category: 'OPD', color: 'blue' },
    { id: 'rm-genmed', blockId: 'blk-b', floorId: 'flr-b-g', roomNumber: 'General Medicine OPD', name: 'General Medicine OPD', category: 'OPD', color: 'blue' },
    { id: 'rm-ortho', blockId: 'blk-b', floorId: 'flr-b-1', roomNumber: 'Orthopedics Clinic', name: 'Orthopedics Clinic', category: 'OPD', color: 'blue' },
    { id: 'rm-xray', blockId: 'blk-c', floorId: 'flr-c-g', roomNumber: 'Digital Chest X-Ray Suite', name: 'Digital Chest X-Ray Suite', category: 'Diagnostic', color: 'orange' },
    { id: 'rm-lab', blockId: 'blk-c', floorId: 'flr-c-1', roomNumber: 'Biochemistry & Pathology Lab', name: 'Biochemistry & Pathology Lab', category: 'Diagnostic', color: 'green' },
    { id: 'rm-ct', blockId: 'blk-c', floorId: 'flr-c-g', roomNumber: '128-Slice CT Scanner', name: '128-Slice CT Scanner', category: 'Diagnostic', color: 'orange' },
    { id: 'rm-derma', blockId: 'blk-b', floorId: 'flr-b-1', roomNumber: 'Dermatology Clinic', name: 'Dermatology Clinic', category: 'OPD', color: 'blue' },
  ];

  const departments: Department[] = [
    {
      id: 'dept-reg',
      hospitalId,
      code: 'REG',
      name: 'Central Registration & Triage',
      nameTa: 'மைய பதிவு மற்றும் வரிசை எண் பிரிவு',
      category: 'registration',
      color: 'yellow',
      blockName: 'Block A',
      floorName: 'Ground Floor',
      roomNumber: 'Central Registration',
      activeCounters: 5,
      totalCounters: 6,
      avgServiceMinutes: 2.2,
      isBottleneck: false,
    },
    {
      id: 'dept-cardio',
      hospitalId,
      code: 'CARDIO',
      name: 'Cardiology (OPD)',
      nameTa: 'இதயவியல் பிரிவு (கார்டியாலஜி)',
      category: 'opd',
      color: 'blue',
      blockName: 'Block B',
      floorName: '1st Floor',
      roomNumber: 'Cardiology OPD Suite',
      activeCounters: 2,
      totalCounters: 3,
      avgServiceMinutes: 6.5,
      isBottleneck: false,
    },
    {
      id: 'dept-genmed',
      hospitalId,
      code: 'GENMED',
      name: 'General Medicine (OPD)',
      nameTa: 'பொது மருத்துவ பிரிவு (OPD)',
      category: 'opd',
      color: 'blue',
      blockName: 'Block B',
      floorName: 'Ground Floor',
      roomNumber: 'General Medicine OPD',
      activeCounters: 4,
      totalCounters: 5,
      avgServiceMinutes: 5.0,
      isBottleneck: false,
    },
    {
      id: 'dept-ortho',
      hospitalId,
      code: 'ORTHO',
      name: 'Orthopedics (OPD)',
      nameTa: 'எலும்பு மூட்டு சிகிச்சை பிரிவு',
      category: 'opd',
      color: 'blue',
      blockName: 'Block B',
      floorName: '1st Floor',
      roomNumber: 'Orthopedics Clinic',
      activeCounters: 3,
      totalCounters: 3,
      avgServiceMinutes: 7.2,
      isBottleneck: false,
    },
    {
      id: 'dept-derma',
      hospitalId,
      code: 'DERMA',
      name: 'Dermatology (OPD)',
      nameTa: 'தோல் நோய் சிகிச்சை பிரிவு',
      category: 'opd',
      color: 'blue',
      blockName: 'Block B',
      floorName: '1st Floor',
      roomNumber: 'Dermatology Clinic',
      activeCounters: 2,
      totalCounters: 2,
      avgServiceMinutes: 5.0,
      isBottleneck: false,
    },
    {
      id: 'dept-xray',
      hospitalId,
      code: 'X-RAY',
      name: 'Digital X-Ray Department',
      nameTa: 'டிஜிட்டல் எக்ஸ்-ரே பிரிவு',
      category: 'diagnostic',
      color: 'orange',
      blockName: 'Block C (Diagnostic)',
      floorName: 'Ground Floor',
      roomNumber: 'Digital Chest X-Ray Suite',
      activeCounters: 2,
      totalCounters: 2,
      avgServiceMinutes: 8.0,
      isBottleneck: false,
    },
    {
      id: 'dept-lab',
      hospitalId,
      code: 'LAB',
      name: 'Central Biochemistry Lab',
      nameTa: 'மைய உயிர்வேதியியல் ஆய்வகம்',
      category: 'diagnostic',
      color: 'green',
      blockName: 'Block C',
      floorName: '1st Floor',
      roomNumber: 'Biochemistry & Pathology Lab',
      activeCounters: 3,
      totalCounters: 4,
      avgServiceMinutes: 4.0,
      isBottleneck: false,
    },
    {
      id: 'dept-ct',
      hospitalId,
      code: 'CT',
      name: '128-Slice CT Scan Unit',
      nameTa: 'சி.டி. ஸ்கேன் பிரிவு',
      category: 'diagnostic',
      color: 'orange',
      blockName: 'Block C',
      floorName: 'Ground Floor',
      roomNumber: '128-Slice CT Scanner',
      activeCounters: 1,
      totalCounters: 1,
      avgServiceMinutes: 12.0,
      isBottleneck: false,
    },
    {
      id: 'dept-pharm',
      hospitalId,
      code: 'PHARM',
      name: 'Central Pharmacy & Dispensing',
      nameTa: 'மைய மருந்தகம் மற்றும் மருந்துகள் வழங்கும் பிரிவு',
      category: 'pharmacy',
      color: 'purple',
      blockName: 'Block A',
      floorName: 'Ground Floor',
      roomNumber: 'Central Pharmacy',
      activeCounters: 4,
      totalCounters: 5,
      avgServiceMinutes: 2.5,
      isBottleneck: false,
    },
    {
      id: 'dept-emerg',
      hospitalId,
      code: 'EMERG',
      name: 'Emergency & Trauma Care (24x7)',
      nameTa: 'அவசர சிகிச்சை மற்றும் விபத்து பிரிவு',
      category: 'emergency',
      color: 'red',
      blockName: 'Block A (Emergency Wing)',
      floorName: 'Ground Floor',
      roomNumber: 'Emergency Trauma Ward',
      activeCounters: 6,
      totalCounters: 6,
      avgServiceMinutes: 15.0,
      isBottleneck: false,
    },
  ];

  const users: User[] = [
    { id: 'usr-doc-1', username: 'dr_priya', password: 'password123', role: 'doctor', fullName: 'Dr. Priya Kumar', departmentId: 'dept-genmed', hospitalId, isActive: true },
    { id: 'usr-doc-arun', username: 'dr_arun', password: 'password123', role: 'doctor', fullName: 'Dr. Arun Kumar', departmentId: 'dept-cardio', hospitalId, isActive: true },
    { id: 'usr-doc-meena', username: 'dr_meena', password: 'password123', role: 'doctor', fullName: 'Dr. Meena Sharma', departmentId: 'dept-ortho', hospitalId, isActive: true },
    { id: 'usr-doc-ravi', username: 'dr_ravi', password: 'password123', role: 'doctor', fullName: 'Dr. Ravi Kumar', departmentId: 'dept-derma', hospitalId, isActive: true },
    { id: 'usr-doc-2', username: 'dr_senthil', password: 'password123', role: 'doctor', fullName: 'Dr. M. Senthil Nathan', departmentId: 'dept-genmed', hospitalId, isActive: true },
    { id: 'usr-diag-1', username: 'tech_murugan', password: 'password123', role: 'diagnostic', fullName: 'K. Murugan (Senior Radiographer)', departmentId: 'dept-xray', hospitalId, isActive: true },
    { id: 'usr-pharm-1', username: 'pharm_radha', password: 'password123', role: 'pharmacy', fullName: 'S. Radha (Chief Pharmacist)', departmentId: 'dept-pharm', hospitalId, isActive: true },
    { id: 'usr-phc-1', username: 'phc_alanganallur', password: 'password123', role: 'phc', fullName: 'Dr. V. Rajesh (MO Alanganallur PHC)', hospitalId, isActive: true },
    { id: 'usr-admin-1', username: 'admin_dean', password: 'password123', role: 'admin', fullName: 'Medical Superintendent / Dean Console', hospitalId, isActive: true },
  ];

  const defaultPatient: Patient = {
    id: 'pat-demo-01',
    name: '9876543210',
    nameTa: '9876543210',
    age: 30,
    gender: 'Other',
    phone: '9876543210',
    abhaId: '91-1234-5678-9012',
    preferredLanguage: 'ta',
    isSynthetic: false,
  };

  // Initialize fresh demo state: 1 default demo patient, 0 journeys, 0 queues, 0 orders
  db.setRawData({
    hospitals: [hospital],
    blocks,
    floors,
    rooms,
    departments,
    users,
    patients: [defaultPatient],
    journeys: [],
    journeyStages: [],
    queueEntries: [],
    consultations: [],
    diagnosticOrders: [],
    pharmacyOrders: [],
    phcReferrals: [],
    notifications: [],
    serviceCounters: [],
    auditLogs: [],
    sequences: {
      journeyCount: 0,
      tokens: {},
    },
  });

  console.log('✅ Clean database seeded successfully with default demo patient (9876543210).');
}
