import { db } from './database';
import {
  Hospital,
  Block,
  Floor,
  Room,
  Department,
  User,
  Patient,
  Journey,
  JourneyStage,
  QueueEntry,
  PHCReferral,
  Notification,
} from './types';

export function seedDatabase() {
  console.log('🌱 Seeding database with configurable hospital infrastructure and synthetic patients...');

  const hospitalId = 'hosp-grh-01';
  const hospital: Hospital = {
    id: hospitalId,
    name: 'Government Rajaji General Hospital',
    location: 'Madurai, Tamil Nadu',
    state: 'Tamil Nadu',
    totalBeds: 1450,
    icuBedsAvailable: 4,
    emergencyBedsAvailable: 8,
    contactPhone: '+91 452 2532535',
    emergencyStatus: 'normal',
    createdAt: new Date().toISOString(),
  };

  const blocks: Block[] = [
    { id: 'blk-a', hospitalId, name: 'Block A', description: 'Main Administration, Entrance & Emergency Care' },
    { id: 'blk-b', hospitalId, name: 'Block B', description: 'Outpatient Specialty Clinics (OPD)' },
    { id: 'blk-c', hospitalId, name: 'Block C', description: 'Radiology, Diagnostics & Imaging Wing' },
  ];

  const floors: Floor[] = [
    { id: 'flr-a-g', blockId: 'blk-a', level: 0, name: 'Ground Floor' },
    { id: 'flr-b-g', blockId: 'blk-b', level: 0, name: 'Ground Floor' },
    { id: 'flr-b-1', blockId: 'blk-b', level: 1, name: '1st Floor' },
    { id: 'flr-c-g', blockId: 'blk-c', level: 0, name: 'Ground Floor' },
    { id: 'flr-c-1', blockId: 'blk-c', level: 1, name: '1st Floor' },
  ];

  const rooms: Room[] = [
    { id: 'rm-reg', blockId: 'blk-a', floorId: 'flr-a-g', roomNumber: 'Counters 1-6', name: 'Central Registration', category: 'Registration', color: 'yellow' },
    { id: 'rm-pharm', blockId: 'blk-a', floorId: 'flr-a-g', roomNumber: 'Counter 3', name: 'Central Pharmacy', category: 'Pharmacy', color: 'purple' },
    { id: 'rm-emerg', blockId: 'blk-a', floorId: 'flr-a-g', roomNumber: 'Triage 1-4', name: 'Emergency Trauma Ward', category: 'Emergency', color: 'red' },
    { id: 'rm-cardio', blockId: 'blk-b', floorId: 'flr-b-1', roomNumber: 'Room 12', name: 'Cardiology OPD Suite', category: 'OPD', color: 'blue' },
    { id: 'rm-genmed', blockId: 'blk-b', floorId: 'flr-b-g', roomNumber: 'Rooms 4-8', name: 'General Medicine OPD', category: 'OPD', color: 'blue' },
    { id: 'rm-ortho', blockId: 'blk-b', floorId: 'flr-b-1', roomNumber: 'Rooms 14-16', name: 'Orthopedics Clinic', category: 'OPD', color: 'blue' },
    { id: 'rm-xray', blockId: 'blk-c', floorId: 'flr-c-g', roomNumber: 'Room 18', name: 'Digital Chest X-Ray Suite', category: 'Diagnostic', color: 'orange' },
    { id: 'rm-lab', blockId: 'blk-c', floorId: 'flr-c-1', roomNumber: 'Lab 101', name: 'Biochemistry & Pathology Lab', category: 'Diagnostic', color: 'green' },
    { id: 'rm-ct', blockId: 'blk-c', floorId: 'flr-c-g', roomNumber: 'CT Suite 2', name: '128-Slice CT Scanner', category: 'Diagnostic', color: 'orange' },
  ];

  const departments: Department[] = [
    {
      id: 'dept-reg',
      hospitalId,
      code: 'REG',
      name: 'Central Registration & Triage',
      nameTa: 'மைய பதிவு மற்றும் வரிசை எண் பிரிவு',
      category: 'registration',
      color: 'yellow',
      blockName: 'Block A',
      floorName: 'Ground Floor',
      roomNumber: 'Counters 1-6',
      activeCounters: 5,
      totalCounters: 6,
      avgServiceMinutes: 2.2,
      isBottleneck: false,
    },
    {
      id: 'dept-cardio',
      hospitalId,
      code: 'CARDIO',
      name: 'Cardiology (OPD)',
      nameTa: 'இதயவியல் பிரிவு (கார்டியாலஜி)',
      category: 'opd',
      color: 'blue',
      blockName: 'Block B',
      floorName: '1st Floor',
      roomNumber: 'Room 12',
      activeCounters: 2,
      totalCounters: 3,
      avgServiceMinutes: 6.5,
      isBottleneck: false,
    },
    {
      id: 'dept-genmed',
      hospitalId,
      code: 'GENMED',
      name: 'General Medicine (OPD)',
      nameTa: 'பொது மருத்துவ பிரிவு (OPD)',
      category: 'opd',
      color: 'blue',
      blockName: 'Block B',
      floorName: 'Ground Floor',
      roomNumber: 'Rooms 4-8',
      activeCounters: 4,
      totalCounters: 5,
      avgServiceMinutes: 5.0,
      isBottleneck: false,
    },
    {
      id: 'dept-ortho',
      hospitalId,
      code: 'ORTHO',
      name: 'Orthopedics (OPD)',
      nameTa: 'எலும்பு மூட்டு சிகிச்சை பிரிவு',
      category: 'opd',
      color: 'blue',
      blockName: 'Block B',
      floorName: '1st Floor',
      roomNumber: 'Rooms 14-16',
      activeCounters: 3,
      totalCounters: 3,
      avgServiceMinutes: 7.2,
      isBottleneck: false,
    },
    {
      id: 'dept-xray',
      hospitalId,
      code: 'X-RAY',
      name: 'Digital X-Ray Department',
      nameTa: 'டிஜிட்டல் எக்ஸ்-ரே பிரிவு',
      category: 'diagnostic',
      color: 'orange',
      blockName: 'Block C (Diagnostic)',
      floorName: 'Ground Floor',
      roomNumber: 'Room 18',
      activeCounters: 1,
      totalCounters: 2,
      avgServiceMinutes: 8.5,
      isBottleneck: true,
      bottleneckReason: 'Queue surged by 38% after Morning OPD rush. Only Counter 1 is currently active.',
    },
    {
      id: 'dept-lab',
      hospitalId,
      code: 'LAB',
      name: 'Central Biochemistry Lab',
      nameTa: 'மைய உயிர்வேதியியல் ஆய்வகம்',
      category: 'diagnostic',
      color: 'green',
      blockName: 'Block C',
      floorName: '1st Floor',
      roomNumber: 'Lab 101',
      activeCounters: 3,
      totalCounters: 4,
      avgServiceMinutes: 4.0,
      isBottleneck: false,
    },
    {
      id: 'dept-ct',
      hospitalId,
      code: 'CT',
      name: '128-Slice CT Scan Unit',
      nameTa: 'சி.டி. ஸ்கேன் பிரிவு',
      category: 'diagnostic',
      color: 'orange',
      blockName: 'Block C',
      floorName: 'Ground Floor',
      roomNumber: 'CT Suite 2',
      activeCounters: 1,
      totalCounters: 1,
      avgServiceMinutes: 12.0,
      isBottleneck: false,
    },
    {
      id: 'dept-pharm',
      hospitalId,
      code: 'PHARM',
      name: 'Central Pharmacy Dispensing',
      nameTa: 'மைய மருந்தகம் மற்றும் மருந்துகள் வழங்கும் பிரிவு',
      category: 'pharmacy',
      color: 'purple',
      blockName: 'Block A',
      floorName: 'Ground Floor',
      roomNumber: 'Counter 3',
      activeCounters: 4,
      totalCounters: 5,
      avgServiceMinutes: 2.8,
      isBottleneck: false,
    },
    {
      id: 'dept-emerg',
      hospitalId,
      code: 'EMERG',
      name: 'Emergency & Trauma Care (24x7)',
      nameTa: 'அவசர சிகிச்சை மற்றும் விபத்து பிரிவு',
      category: 'emergency',
      color: 'red',
      blockName: 'Block A (Emergency Wing)',
      floorName: 'Ground Floor',
      roomNumber: 'Triage 1-4',
      activeCounters: 6,
      totalCounters: 6,
      avgServiceMinutes: 15.0,
      isBottleneck: false,
    },
  ];

  const users: User[] = [
    { id: 'usr-doc-1', username: 'dr_priya', role: 'doctor', fullName: 'Dr. Priya Kumar, MD, DM', departmentId: 'dept-cardio', hospitalId, isActive: true },
    { id: 'usr-doc-2', username: 'dr_senthil', role: 'doctor', fullName: 'Dr. M. Senthil Nathan, MD', departmentId: 'dept-genmed', hospitalId, isActive: true },
    { id: 'usr-diag-1', username: 'tech_murugan', role: 'diagnostic', fullName: 'K. Murugan (Senior Radiographer)', departmentId: 'dept-xray', hospitalId, isActive: true },
    { id: 'usr-pharm-1', username: 'pharm_radha', role: 'pharmacy', fullName: 'S. Radha (Chief Pharmacist)', departmentId: 'dept-pharm', hospitalId, isActive: true },
    { id: 'usr-phc-1', username: 'phc_alanganallur', role: 'phc', fullName: 'Dr. V. Rajesh (MO Alanganallur PHC)', hospitalId, isActive: true },
    { id: 'usr-admin-1', username: 'admin_dean', role: 'admin', fullName: 'Medical Superintendent / Dean Console', hospitalId, isActive: true },
  ];

  // Synthetic Patients
  const patients: Patient[] = [
    {
      id: 'P-8942',
      name: 'Ravi Kumar',
      nameTa: 'ரவி குமார்',
      age: 58,
      gender: 'Male',
      phone: '98401 23456',
      abhaId: '91-4829-1029-4821',
      preferredLanguage: 'ta',
      isSynthetic: true,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'P-8939',
      name: 'Meenakshi Sundaram',
      nameTa: 'மீனாட்சி சுந்தரம்',
      age: 64,
      gender: 'Female',
      phone: '94432 98112',
      abhaId: '91-3312-8871-9920',
      preferredLanguage: 'ta',
      isSynthetic: true,
      createdAt: new Date(Date.now() - 4000000).toISOString(),
    },
    {
      id: 'P-8940',
      name: 'K. Balaji',
      nameTa: 'கே. பாலாஜி',
      age: 42,
      gender: 'Male',
      phone: '97890 54321',
      abhaId: '91-9941-2234-5511',
      preferredLanguage: 'en',
      isSynthetic: true,
      createdAt: new Date(Date.now() - 3800000).toISOString(),
    },
    {
      id: 'P-8931',
      name: 'S. Shanmugam',
      nameTa: 'எஸ். சண்முகம்',
      age: 51,
      gender: 'Male',
      phone: '98411 90234',
      abhaId: '91-1123-9988-4432',
      preferredLanguage: 'ta',
      isSynthetic: true,
      createdAt: new Date(Date.now() - 4500000).toISOString(),
    },
    {
      id: 'P-8915',
      name: 'Anjalai Ammal',
      nameTa: 'அஞ்சலை அம்மாள்',
      age: 69,
      gender: 'Female',
      phone: '94440 12890',
      abhaId: '91-8876-5544-2210',
      preferredLanguage: 'ta',
      isSynthetic: true,
      createdAt: new Date(Date.now() - 5000000).toISOString(),
    },
  ];

  // Journeys
  const journeys: Journey[] = [
    {
      id: 'JNY-20260902-00042',
      patientId: 'P-8942',
      hospitalId,
      initialDepartmentId: 'dept-cardio',
      currentDepartmentId: 'dept-cardio',
      currentStage: 'doctor',
      currentToken: 'CARDIO-042',
      status: 'active',
      priority: 'senior',
      vitals: { bp: '148/94 mmHg', pulse: '84 bpm', temp: '98.4 °F', spo2: '98%' },
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'JNY-20260902-00039',
      patientId: 'P-8939',
      hospitalId,
      initialDepartmentId: 'dept-cardio',
      currentDepartmentId: 'dept-cardio',
      currentStage: 'doctor',
      currentToken: 'CARDIO-039',
      status: 'active',
      priority: 'senior',
      vitals: { bp: '135/85 mmHg', pulse: '76 bpm', temp: '98.6 °F', spo2: '99%' },
      createdAt: new Date(Date.now() - 4000000).toISOString(),
    },
    {
      id: 'JNY-20260902-00040',
      patientId: 'P-8940',
      hospitalId,
      initialDepartmentId: 'dept-cardio',
      currentDepartmentId: 'dept-cardio',
      currentStage: 'doctor',
      currentToken: 'CARDIO-040',
      status: 'active',
      priority: 'normal',
      vitals: { bp: '128/82 mmHg', pulse: '72 bpm', temp: '98.2 °F', spo2: '99%' },
      createdAt: new Date(Date.now() - 3800000).toISOString(),
    },
    {
      id: 'JNY-20260902-00031',
      patientId: 'P-8931',
      hospitalId,
      initialDepartmentId: 'dept-xray',
      currentDepartmentId: 'dept-xray',
      currentStage: 'diagnostic',
      currentToken: 'X-RAY-031',
      status: 'active',
      priority: 'normal',
      vitals: { bp: '130/80 mmHg', pulse: '78 bpm', temp: '98.6 °F', spo2: '98%' },
      createdAt: new Date(Date.now() - 4500000).toISOString(),
    },
    {
      id: 'JNY-20260902-00015',
      patientId: 'P-8915',
      hospitalId,
      initialDepartmentId: 'dept-pharm',
      currentDepartmentId: 'dept-pharm',
      currentStage: 'pharmacy',
      currentToken: 'PHARM-015',
      status: 'active',
      priority: 'senior',
      vitals: { bp: '140/88 mmHg', pulse: '80 bpm', temp: '98.4 °F', spo2: '97%' },
      createdAt: new Date(Date.now() - 5000000).toISOString(),
    },
  ];

  // Journey Stages
  const journeyStages: JourneyStage[] = [
    {
      id: 'STG-42-1',
      journeyId: 'JNY-20260902-00042',
      stageType: 'registration',
      departmentId: 'dept-reg',
      tokenNumber: 'REG-8942',
      sequenceNum: 1,
      status: 'completed',
      roomNumber: 'Counters 1-6',
      blockName: 'Block A',
      floorName: 'Ground Floor',
      color: 'yellow',
      notes: 'Initial registration and triage vitals checked',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      completedAt: new Date(Date.now() - 3300000).toISOString(),
    },
    {
      id: 'STG-42-2',
      journeyId: 'JNY-20260902-00042',
      stageType: 'doctor',
      departmentId: 'dept-cardio',
      tokenNumber: 'CARDIO-042',
      sequenceNum: 2,
      status: 'waiting',
      roomNumber: 'Room 12',
      blockName: 'Block B',
      floorName: '1st Floor',
      color: 'blue',
      notes: 'Waiting for Dr. Priya Kumar',
      createdAt: new Date(Date.now() - 3300000).toISOString(),
    },
  ];

  // Queue Entries
  const queueEntries: QueueEntry[] = [
    {
      id: 'QE-39',
      departmentId: 'dept-cardio',
      journeyId: 'JNY-20260902-00039',
      journeyStageId: 'STG-39-2',
      patientId: 'P-8939',
      tokenNumber: 'CARDIO-039',
      sequenceNum: 39,
      status: 'called',
      priority: 'senior',
      calledAt: new Date(Date.now() - 120000).toISOString(),
      createdAt: new Date(Date.now() - 4000000).toISOString(),
    },
    {
      id: 'QE-40',
      departmentId: 'dept-cardio',
      journeyId: 'JNY-20260902-00040',
      journeyStageId: 'STG-40-2',
      patientId: 'P-8940',
      tokenNumber: 'CARDIO-040',
      sequenceNum: 40,
      status: 'waiting',
      priority: 'normal',
      createdAt: new Date(Date.now() - 3800000).toISOString(),
    },
    {
      id: 'QE-42',
      departmentId: 'dept-cardio',
      journeyId: 'JNY-20260902-00042',
      journeyStageId: 'STG-42-2',
      patientId: 'P-8942',
      tokenNumber: 'CARDIO-042',
      sequenceNum: 42,
      status: 'waiting',
      priority: 'senior',
      createdAt: new Date(Date.now() - 3300000).toISOString(),
    },
    {
      id: 'QE-XRAY-31',
      departmentId: 'dept-xray',
      journeyId: 'JNY-20260902-00031',
      journeyStageId: 'STG-31-1',
      patientId: 'P-8931',
      tokenNumber: 'X-RAY-031',
      sequenceNum: 31,
      status: 'waiting',
      priority: 'normal',
      createdAt: new Date(Date.now() - 4500000).toISOString(),
    },
    {
      id: 'QE-PHARM-15',
      departmentId: 'dept-pharm',
      journeyId: 'JNY-20260902-00015',
      journeyStageId: 'STG-15-1',
      patientId: 'P-8915',
      tokenNumber: 'PHARM-015',
      sequenceNum: 15,
      status: 'waiting',
      priority: 'senior',
      createdAt: new Date(Date.now() - 5000000).toISOString(),
    },
  ];

  // Referrals
  const phcReferrals: PHCReferral[] = [
    {
      id: 'REF-TN-2026-091',
      patientName: 'Kuppusamy M.',
      patientAge: 62,
      patientGender: 'Male',
      fromPhcName: 'Alanganallur Primary Health Centre (PHC)',
      targetHospitalId: hospitalId,
      targetHospitalName: 'Government Rajaji General Hospital',
      specialty: 'Cardiology',
      clinicalReason: 'Acute Chest Pain, ST elevation noted in Lead II, III, aVF. Suspected Inferior Wall MI.',
      urgency: 'emergency',
      status: 'accepted',
      assignedToken: 'CARDIO-EMERG-003',
      distanceKm: 18,
      travelMinutes: 32,
      icuBedsAvailable: 4,
      hospitalLoadPercent: 62,
      createdAt: new Date(Date.now() - 1800000).toISOString(),
      updatedAt: new Date(Date.now() - 1200000).toISOString(),
    },
    {
      id: 'REF-TN-2026-088',
      patientName: 'Kavitha R.',
      patientAge: 34,
      patientGender: 'Female',
      fromPhcName: 'Vadipatti Upgraded PHC',
      targetHospitalId: hospitalId,
      targetHospitalName: 'Government Rajaji General Hospital',
      specialty: 'Orthopedics',
      clinicalReason: 'Compound fracture tibia fibula right leg following road traffic accident.',
      urgency: 'urgent',
      status: 'en_route',
      assignedToken: 'ORTHO-EMERG-007',
      distanceKm: 24,
      travelMinutes: 38,
      icuBedsAvailable: 4,
      hospitalLoadPercent: 62,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 2400000).toISOString(),
    },
  ];

  // Notifications
  const notifications: Notification[] = [
    {
      id: 'notif-1',
      targetRole: 'admin',
      title: 'Digital X-Ray Bottleneck Warning',
      titleTa: 'எக்ஸ்-ரே பிரிவு காத்திருப்பு எச்சரிக்கை',
      message: 'Queue exceeded 90% load threshold (67 waiting, ETA 95m). Recommended: Open Counter 2.',
      messageTa: 'எக்ஸ்-ரே பிரிவில் கூட்டம் அதிகரித்துள்ளது. கவுண்டர் 2-ஐ திறக்கவும்.',
      type: 'critical',
      isRead: false,
      createdAt: new Date(Date.now() - 900000).toISOString(),
    },
    {
      id: 'notif-2',
      targetRole: 'patient',
      targetJourneyId: 'JNY-20260902-00042',
      title: 'Queue Position Update',
      titleTa: 'வரிசை எண் நிலை மாற்றம்',
      message: 'Token CARDIO-042: 2 patients ahead (~7 min wait). Please wait near Room 12.',
      messageTa: 'டோக்கன் CARDIO-042: உங்களுக்கு முன் 2 நபர்கள் உள்ளனர். அறை 12 அருகில் இருக்கவும்.',
      type: 'info',
      isRead: false,
      createdAt: new Date(Date.now() - 300000).toISOString(),
    },
  ];

  db.setRawData({
    hospitals: [hospital],
    blocks,
    floors,
    rooms,
    departments,
    users,
    patients,
    journeys,
    journeyStages,
    queueEntries,
    consultations: [],
    diagnosticOrders: [],
    pharmacyOrders: [],
    phcReferrals,
    notifications,
    serviceCounters: [],
    auditLogs: [],
    sequences: {
      journeyCount: 42,
      tokens: {
        CARDIO: 42,
        GENMED: 85,
        ORTHO: 28,
        'X-RAY': 31,
        LAB: 45,
        CT: 12,
        PHARM: 15,
        REG: 184,
      },
    },
  });

  console.log('✅ Database seeded successfully.');
}
